# отдельно настраивается для каждого окружения, на котором нам нужны переменные (PROD, DEV, STAGE)
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config-map # имя по которому будем обращаться
data: # сами наши переменные с их значениями
  NODE_ENV: "STAGING"
  AUTH_SERVICE_API: "https://google.com/auth"
