name: build and push docker image # при изменении основной ветки нашего проекта, автоматически будет собираться наш образ и пушиться на dockerhub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # стягиваем наш репозиторий на виртуальную машину

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # плагин устанавливает докер

      - name: Log in to Docker Hub
        uses: docker/login-action@v2 # плагин для логина в докер хаб
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3  # плагин для пуша в докер хаб
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/backend-devops:latest



