name: env variables

on: [push]

env:
  NODE_ENV: production # задаем переменную в самом файле
  TEST_ENV: ${{ vars.DOCKER_USERNAME }} # достаем переменную из гитхаба settings->actions->variables
  TEST_SECRET: ${{ secrets.DOCKER_TOKEN }} # достаем переменную из гитхаба settings->actions->secrets

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Display env variables
        run: | 
          echo NODE_ENV is $NODE_ENV
          echo TEST_ENV is $TEST_ENV
          echo TEST_SECRET is $TEST_SECRET
          

