version: "3"

services:
  frontend:
    build:
      context: ./frontend #где лежит Dockerfile
      args:
        PORT: "3000"
    ports:
      - "3001:3000"
    depends_on:
      - backend #здесь мы говорим, что этот сервис зависит от сервиса backend и frontend не будет запущен, пока не запустится backend
  backend:
    build:
      context: ./backend #где лежит Dockerfile
      args:
        PORT: '5005'
    ports:
      - "3002:5005"
    environment:
      PORT: "5005"


