apiVersion: v1 # версия сущности в k8s кластере
kind: Service # какая сущность будет развернута
metadata:
  name: nginx-service
spec: # спецификация сервиса
  type: NodePort
  selector:  # по какому селектору выбирать наш под (labels)
    app: nginx-pod
  ports:
    - protocol: TCP
      port: 80 # порт который открывается на сервисе, для доступа к нему
      targetPort: 80 # порт который разворачивается в контейнере (указан в докер образе?, или указываем при запуске контейнера)
      nodePort: 30007 # порт который открывается для нашей ноды (виртуальной машины или железки), то есть мы стучимся на него, нода стучится к сервису, сервис стучится к поду, в котором запущен контейнер на конкретном порту
