name: run tests on pull request to production

on:
  pull_request: # запустится на открытие пулл реквеста в основную ветку
    branches:
      - production

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # стягиваем репозиторий на машину

      - name: Set up Node.js
        uses: actions/setup-node@v2 # плагин устанавливает ноду на машину
        with:
          node-version: '20'

      - name: Install dependencies # устанавливаем зависимости
        run: |
          cd /home/runner/work/docker-advanced/backend 
          npm install

      - name: Run test  # запускаем тесты
        run: |
          cd /home/runner/work/docker-advanced/backend 
          npm test
